steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    # CHANGE us-west1 to us-central1 (or your working region) below:
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-now-repo/weather-app:latest', '.']

  # Step 2: Push the image to the Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    # CHANGE us-west1 to us-central1 (or your working region) below:
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-now-repo/weather-app:latest']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'weather-service'
      - '--image'
      # CHANGE us-west1 to us-central1 (or your working region) below:
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/weather-now-repo/weather-app:latest'
      - '--region'
      # CHANGE us-west1 to us-central1 (or your working region) below:
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
